project_novis/callsign/urls.py
from django.urls import path

from .views import CallsignDetailView, CallsignCreate, CallsignUpdate, CallsignClaimView, RepeaterUpdate, ClubUpdate,\
    CallsignAutocomplete

app_name = "callsign"

urlpatterns = [
    path('add/', CallsignCreate.as_view(), name='callsign-html-create'),
    path('autocomplete/', CallsignAutocomplete.as_view(), name='callsign-autocomplete'),

    path('<slug>/', CallsignDetailView.as_view(), name='callsign-html-detail'),
    path('<slug>/change', CallsignUpdate.as_view(), name='callsign-html-update'),
    path('<slug>/repeater/change', RepeaterUpdate.as_view(), name='repeater-html-update'),
    path('<slug>/club/change', ClubUpdate.as_view(), name='club-html-update'),
    path('<slug>/claim', CallsignClaimView.as_view(), name='callsign-html-claim'),
]

project_novis/project_novis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('', include('callsign.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.views import defaults as default_views
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

project_novis/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.views.decorators.cache import cache_page

from project_novis.main.sitemaps import StaticViewSitemap
from project_novis.callsign.sitemaps import CallsignSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'flatpages': FlatPageSitemap,
    'callsigns': CallsignSitemap
}

urlpatterns = [
    path('', include('project_novis.main.urls')),
    path('accounts/', include('project_novis.accounts.urls')),
    path('.well-known/change-password', RedirectView.as_view(pattern_name='account_change_password', permanent=False)),
    path('sitemap.xml', cache_page(3600)(sitemaps_views.index), {'sitemaps': sitemaps}, name="sitemap"),
    path('sitemap-<section>.xml', cache_page(3600)(sitemaps_views.sitemap), {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path('c/', include('project_novis.callsign.urls')),
    path("api/v1/", include("project_novis.api.urls", namespace='v1')),
    path('', include('project_novis.radius.urls')),
    path('admin/', admin.site.urls),
    path('docs/', RedirectView.as_view(url=settings.DOCS_URL, permanent=False), name='docs'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    from django.views import defaults as default_views
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            path('__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

project_novis/callsign/models.py
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.contrib.gis.db import models
from django.contrib.gis.geos import Point
from django.contrib.postgres.fields import JSONField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import PermissionDenied, ValidationError

from .enums import CALLSIGN_TYPES, CONTINENTS, CTCSS, RF_MODES, BLACKLIST_REASONS,\
    LOCATION_SOURCE_CHOICES, LOCATION_SOURCE_PRIORITY
from .utils import CallsignField, CQZoneField, ITUZoneField, ITURegionField, WikidataObjectField,\
    generate_aprs_passcode, point_to_grid, grid_to_point, get_sentinel_user


class BaseModel(models.Model):
    created = models.DateTimeField(_("Created"), auto_now_add=True)
    modified = models.DateTimeField(_("Modified"), auto_now=True)

    class Meta:
        abstract = True


class LocationBaseModel(BaseModel):
    location = models.PointField(null=True, blank=True)

    class Meta:
        abstract = True

    def _grid(self, high_accuracy: bool = True) -> str:
        if not self.location:
            return ""

        return point_to_grid(self.location, high_accuracy=high_accuracy)

    @property
    def grid(self):
        return self._grid(high_accuracy=True)

    @grid.setter
    def grid(self, grid: str):
        self.location = grid_to_point(grid)

    @property
    def aprs_fi_url(self) -> str:
        return f"https://aprs.fi/#!addr={self.grid}"

    # @property
    # def cq_zone(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def itu_zone(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def itu_region(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def continent(self) -> str:
    #     raise NotImplementedError
    #
    # @property
    # def dxcc(self) -> int:
    #     raise NotImplementedError
    #
    # @property
    # def country(self) -> str:
    #     raise NotImplementedError
    #
    # @property
    # def utc_offset(self) -> int:
    #     raise NotImplementedError


class Country(BaseModel):
    name = models.CharField(max_length=64, unique=True, db_index=True)
    alpha_2 = models.CharField(max_length=2, unique=True, db_index=True, help_text="ISO 3166-1 alpha-2 – two-letter country code")
    alpha_3 = models.CharField(max_length=3, unique=True, db_index=True, help_text="ISO 3166-1 alpha-3 – three-letter country code")
    numeric_3 = models.CharField(max_length=3, unique=True, db_index=True, help_text="ISO 3166-1 numeric – three-digit country code")
    wikidata_object = WikidataObjectField(unique=True, db_index=True)

    # Additional Information
    adif_name = models.CharField("ADIF name", max_length=64, db_index=True, blank=True, null=True, help_text="Amateur Data Interchange Format (ADIF) country name")
    geonames_id = models.PositiveIntegerField("Geonames ID", null=True, blank=True)
    osm_relation_id = models.PositiveIntegerField("OSM relation ID", null=True, blank=True, help_text="OpenStreetMap relation ID")
    itu_object_identifier = models.CharField("ITU object identifier", max_length=16, blank=True, null=True, help_text="International Telecommunication Union (ITU) object identifier")
    itu_letter_code = models.CharField("ITU letter code", max_length=3, blank=True, null=True, help_text="International Telecommunication Union (ITU) letter code")
    fips = models.CharField("FIPS", max_length=2, blank=True, null=True, help_text="Federal Information Processing Standards (FIPS) 10-4 standard country code")

    def __str__(self) -> str:
        return self.name

    @property
    def wikidata_url(self) -> str:
        return f"https://www.wikidata.org/wiki/{self.wikidata_object}"

    @property
    def geonames_url(self) -> str:
        if self.geonames_id:
            return f"https://www.geonames.org/{self.geonames_id}"
        else:
            return ""

    @property
    def osm_relation_url(self) -> str:
        if self.osm_relation_id:
            return f"https://www.openstreetmap.org/relation/{self.osm_relation_id}"
        else:
            return ""

    @property
    def world_fact_book_url(self) -> str:
        if self.fips:
            return f"https://www.cia.gov/library/publications/the-world-factbook/geos/{self.fips}.html"
        else:
            return ""


class DXCCEntry(BaseModel):
    name = models.CharField(max_length=64, db_index=True)
    deleted = models.BooleanField(default=False)
    country = models.ForeignKey(Country, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "DXCC Entry"
        verbose_name_plural = "DXCC Entries"
        unique_together = ("name", "deleted")


class CallsignPrefix(BaseModel):
    name = models.CharField(max_length=16, unique=True, db_index=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, null=True, blank=True)
    dxcc = models.ForeignKey(DXCCEntry, on_delete=models.PROTECT, null=True, blank=True, verbose_name="DXCC")
    cq_zone = CQZoneField("CQ zone", null=True, blank=True)
    itu_zone = ITUZoneField("ITU zone", null=True, blank=True)
    itu_region = ITURegionField("ITU region", null=True, blank=True)
    continent = models.CharField(choices=CONTINENTS, max_length=2, blank=True)
    location = models.PointField(null=True, blank=True)
    utc_offset = models.FloatField("UTC offset", null=True, blank=True)
    type = models.CharField(choices=CALLSIGN_TYPES, max_length=32, blank=True)

    def __str__(self) -> str:
        return self.name


class CallsignManager(models.Manager):
    def create_callsign(self, callsign: str, created_by_id: int, check_blacklist: bool = True):
        # TODO further validate callsign
        # Check if callsign is blacklisted
        if check_blacklist and CallsignBlacklist.objects.filter(callsign=callsign).exists():
            raise ValidationError("callsign is blacklisted")

        instance = self.create(name=callsign, created_by_id=created_by_id)
        instance.set_default_meta_data()
        instance.save()
        return instance


class Callsign(LocationBaseModel):
    name = CallsignField(unique=True, db_index=True)
    prefix = models.ForeignKey(CallsignPrefix, on_delete=models.PROTECT, null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, null=True, blank=True)
    cq_zone = CQZoneField("CQ zone", null=True, blank=True)
    itu_zone = ITUZoneField("ITU zone", null=True, blank=True)
    itu_region = ITURegionField("ITU region", null=True, blank=True)
    type = models.CharField(choices=CALLSIGN_TYPES, max_length=32, blank=True)
    owner = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)
    active = models.BooleanField(default=True)
    issued = models.DateField(null=True, blank=True)
    expired = models.DateField(null=True, blank=True)
    license_type = models.CharField(max_length=64, blank=True)
    dstar = models.BooleanField("D-STAR", default=False)
    identifier = models.CharField(_("Optional identifier"), max_length=128, unique=True, blank=True, null=True)
    website = models.URLField(max_length=128, blank=True, null=True)
    comment = models.TextField(blank=True)
    _official_validated = models.BooleanField(default=False, help_text="Callsign is validated by a government agency")
    _location_source = models.CharField(max_length=32, choices=LOCATION_SOURCE_CHOICES, blank=True)

    lotw_last_activity = models.DateTimeField("LOTW last activity", null=True, blank=True)
    eqsl = models.BooleanField(default=False)

    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET(get_sentinel_user), related_name="callsigns")
    internal_comment = models.TextField(blank=True)
    source = models.CharField(max_length=256, blank=True)
    objects = CallsignManager()

    # TODO(elnappo) make sure a user can not change his name after validation

    def __str__(self) -> str:
        return self.name

    def set_default_meta_data(self):
        prefix = CallsignPrefix.objects.extra(where=["%s LIKE name||'%%'"], params=[self.name]).order_by("-name").first()

        # Add changed fields to ImportCommand._callsign_bulk_create()
        if prefix:
            self.prefix = prefix
            self.country = prefix.country
            self.cq_zone = prefix.cq_zone
            self.itu_zone = prefix.itu_zone
            self.location = prefix.location
            self._location_source = "prefix"

    def get_absolute_url(self) -> str:
        return reverse('callsign:callsign-html-detail', args=[self.name])

    def update_location(self, location: Point, source: str) -> bool:
        # Update location only if new location source has higher priority than current location source.
        # Does no update if new and current location source are equal.
        if LOCATION_SOURCE_PRIORITY.index(source) > LOCATION_SOURCE_PRIORITY.index(self.location_source):
            self.location = location
            self._location_source = source
            return True
        else:
            return False

    @property
    def aprs_passcode(self) -> int:
        if self.official_validated == "false" or self.type == "shortwave_listener":
            # Not a good idea to raise an exception here?
            raise PermissionDenied("callsign is not official assigned or is shortwave listener")
        return generate_aprs_passcode(self.name)

    @property
    def official_validated(self) -> str:
        if self.country and self.country.telecommunicationagency.used_for_official_callsign_import and self._official_validated:
            return "true"
        elif self.country and self.country.telecommunicationagency.used_for_official_callsign_import and not self._official_validated:
            return "false"
        else:
            return "unknown"

    @property

project_novis/callsign/forms.py
from dal import autocomplete
from django.contrib.gis import forms

from .models import Callsign, Repeater, Club


class CallsignForm(forms.ModelForm):
    issued = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}),
                             required=False)
    location = forms.PointField(srid=4326,
                                widget=forms.OSMWidget(attrs={'map_width': 785, 'map_height': 500, 'default_zoom': 12}))

    class Meta:
        model = Callsign
        fields = ["type", "location", 'cq_zone', "itu_zone", "dstar", "issued"]


class RepeaterForm(forms.ModelForm):

    class Meta:
        model = Repeater
        fields = ["active", "website", 'altitude', "description"]


class ClubForm(forms.ModelForm):

    class Meta:
        model = Club
        fields = ["website", "description", "members"]
        widgets = {
            'members': autocomplete.ModelSelect2Multiple(url='callsign:callsign-autocomplete')
        }

project_novis/callsign/templates/callsign/callsign_create_form.html
{% extends 'index.html' %}
{% load static i18n account crispy_forms_tags %}

{% block title %}Add new call sign{% endblock %}

{% block content_header %}
<h1>
    {{ object.name }}
</h1>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Callsign</a></li>
    <li class="active">Add</li>
</ol>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-8">
        <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">Add new callsign</h3>
            </div>
            <div class="box-body">
                <form class="form" method="post" action="">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary" type="submit" name="action">{% trans "Add" %}</button>
                </form>
            </div>
            <!-- /.box-body -->
        </div>
    </div>
</div>
{% endblock %}

project_novis/callsign/templates/callsign/callsign_detail.html
{% extends 'index.html' %}
{% load static i18n account crispy_forms_tags %}

{% block title %}{{ object.name }} - Amateur Radio Callsign{% endblock %}

{% block meta_content %}
    <meta name="description" content="{{ object.name }} is an amateur radio callsign{% if object.location and object.country.name %} located in {{ object.country.name }} (QTH: {{ object.grid }}){% endif %}. Project novis is a free and open-source platform for amateur radio related services.">
    <meta name="callsign" content="{{ object.name }}">
{% endblock %}

{% block content_header %}
    <h1>
        {{ object.name }}
        {% if object.official_validated == "true" %}
        <i class="fa fa-check-circle" title="Callsign official issued"></i>
        {% elif object.official_validated == "false" %}
        <i class="fa fa-times-circle" title="Callsign not official issued"></i>
        {% endif %}
    </h1>
    <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Callsign</a></li>
        <li class="active">{{ object.name }}</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title">Callsign Information</h3>
                    {% if user == object.owner %}
                        <div class="box-tools pull-right">
                        {% if not object.repeater and object.type == "repeater" %}
                            <a href="{% url "callsign:repeater-html-update" object.name %}"
                               class="btn btn-sm btn-default"><i class="fa fa-plus-square"></i> Add Repeater Information</a>
                        {% endif %}
                        {% if not object.club and object.type == "club" %}
                            <a href="{% url "callsign:club-html-update" object.name %}"
                               class="btn btn-sm btn-default"><i class="fa fa-plus-square"></i> Add Club Information</a>
                        {% endif %}
                            <a href="{% url "callsign:callsign-html-update" object.name %}"
                               class="btn btn-sm btn-default"><i class="fa fa-edit"></i> Edit</a>
                        </div>
                    {% elif object.owner == None %}
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-sm btn-default" data-toggle="modal"
                                    data-target="#callSignClaimModal"><i class="fa fa-plus"></i> Claim
                            </button>
                        </div>
                        <div class="modal fade" id="callSignClaimModal" tabindex="-1" role="dialog"
                             aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Confirm callsign claim</h4>
                                    </div>
                                    <div class="modal-body">
                                        {% if not user.is_authenticated %}
                                            To claim and edit a callsign please create an account <a href="{% url 'account_signup' %}">here</a>.
                                        {% else %}
                                        <p><strong>
                                            Are you sure to claim <mark>{{ object.name }}</mark> to your account?
                                        </strong></p>
                                        {% endif %}
                                        <p>
                                            After you claimed a callsign to your account you can edit details and
                                            validate the ownership to get access to e.g. the APRS passcode.
                                        </p>
                                        {% if user.is_authenticated %}
                                        <form class="form" method="post"
                                              action={% url "callsign:callsign-html-claim" object.name %}>
                                            {% csrf_token %}
                                            <div class="modal-footer">
                                                <button class="btn btn-primary" type="submit" name="action">
                                                    Claim {{ object.name }}</button>
                                            </div>
                                        </form>
                                        {% else %}
                                            <div class="modal-footer">
                                                <a href="{% url 'account_signup' %}" class="btn btn-primary" role="button">Signup</a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div class="box-body no-padding">
                    <table class="table table-hover">
                        <tbody>
                        <tr>
                            <td>Country</td>
                            <td>{{ object.country|default_if_none:"Unknown" }}</td>
                        </tr>
                        <tr>
                            <td>DXCC Entry</td>
                            <td>{% if object.prefix.dxcc %}{{ object.prefix.dxcc }} ({{ object.prefix.dxcc.id }}){% endif %}</td>
                        </tr>
                        <tr>
                            <td>Grid</td>
                            <td>
                                {% if object.grid %}
                                    <div style="font-size: 125%">
                                        <a href="{{ object.aprs_fi_url }}" target="_blank"
                                   rel="noopener"><span class="label label-info label-as-badge"> {{ object.grid }} </span></a>
                                    </div>
                                {% endif %}
                            </td>
                        </tr>
                        <tr>
                            <td>CQ Zone</td>
                            <td>{% if object.cq_zone %}<span class="badge">{{ object.cq_zone }}</span>{% endif %}</td>
                        </tr>
                        <tr>
                            <td>ITU Zone</td>
                            <td>{% if object.itu_zone %}<span class="badge">{{ object.itu_zone }}</span>{% endif %}</td>
                        </tr>
                        <tr>
                            <td>Type</td>
                            <td>{{ object.get_type_display }}</td>
                        </tr>
                        <tr>
                            <td>DMR ID</td>
                            <td>{% for entry in object.dmr_ids.all %}
                                <a href="{{ entry.brandmeister_profile_url }}" target="_blank"
                                   rel="noopener">{{ entry.name }} </a>{% endfor %}</td>
                        </tr>
                        <tr>
                            <td>D-STAR</td>
                            <td>{{ object.dstar|yesno }}</td>
                        </tr>
                        {% if object.issued %}
                        <tr>
                            <td>Issued</td>
                            <td>{{ object.issued }}</td>
                        </tr>
                        {% endif %}
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
          {% if object.repeater %}
            {% include "callsign/repeater_box.html" %}
          {% endif %}
          {% if object.club %}
            {% include "callsign/club_box.html" %}
          {% endif %}
        </div>
        {% if object.location %}
            <div class="col-md-4">
                <div class="box box-info">
                    <div class="box-header with-border">
                        <h3 class="box-title"><i class="fa fa-map margin-r-5"></i> Location</h3>
                    </div>
                    <div class="box-body no-padding">
                        <div id="map" style="width: auto; height: 300px;"></div>
                        <script>
                            function initMap() {
                                var location = {lat: {{ object.location.y }}, lng: {{ object.location.x }}};
                                var map = new google.maps.Map(document.getElementById('map'), {
                                    zoom: 7,
                                    center: location
                                });
                                var marker = new google.maps.Marker({position: location, map: map});
                            }
                        </script>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer text-center">
                      {% if object.location_source == "prefix" %}
                        Location is based on prefix and may be inaccurate.
                      {% else %}
                        Source: {{ object.location_source }}
                      {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="col-md-4 pull-right">
            <div class="box box-info">
                <div class="box-header with-border">
                    <h3 class="box-title"><i class="fa fa-link margin-r-5"></i> Links</h3>
                </div>
                <div class="box-body no-padding">
                    <table class="table table-hover">
                        <tbody>
                        {% if object.lotw %}
                            <tr>
                                <td>LOTW</td>
                            </tr>
                        {% endif %}
                        {% if object.eqsl %}
                            <tr>
                                <td><a href="{{ object.eqsl_profile_url }}" target="_blank" rel="noopener">eQSL</a></td>
                            </tr>
                        {% endif %}
                        {% if object.clubloguser %}
                            <tr>
                                <td><a href="{{ object.clublog_profile_url }}" target="_blank" rel="noopener">Clublog</a>
                                </td>
                            </tr>
                        {% endif %}
                        <tr>
                            <td><a href="{{ object.dxheat_profile_url }}" target="_blank" rel="noopener">DXHeat</a></td>
                        </tr>
                        <tr>
                            <td><a href="{{ object.dxwatch_profile_url }}" target="_blank" rel="noopener">DXWatch</a></td>
                        </tr>
                        <tr>
                            <td><a href="{{ object.aprsfi_profile_url }}" target="_blank" rel="noopener">APRS</a></td>
                        </tr>
                        <tr>
                            <td><a href="{{ object.pskreporter_profile_url }}" target="_blank" rel="noopener">PSKreporter</a></td>
                        </tr>
                        <tr>
                            <td><a href="{{ object.qrz_profile_url }}" target="_blank" rel="noopener">QRZ.com</a></td>
                        </tr>
                        <tr>
                            <td><a href="{{ object.hamqth_profile_url }}" target="_blank" rel="noopener">HamQTH</a></td>
                        </tr>
                        <tr>
                            <td><a href="{{ object.hamcall_profile_url }}" target="_blank" rel="noopener">HamCall</a></td>
                        </tr>
                        <tr>
                            <td><a href="{{ object.qrzcq_profile_url }}" target="_blank" rel="noopener">QRZCQ</a></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_foot %}
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAcml_vhlyb_QC1tyvMwdIXI1xU6UWKvwo&callback=initMap"
            async defer></script>
{% endblock %}

project_novis/callsign/templates/callsign/club_box.html
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Club Information</h3>
        {% if user == object.owner %}
            <div class="box-tools pull-right">
            <a href="{% url "callsign:club-html-update" object.name %}"
                 class="btn btn-sm btn-default"><i class="fa fa-edit"></i> Edit</a>
            </div>
        {% endif %}
    </div>
    <div class="box-body no-padding">
        <table class="table table-hover">
            <tbody>
            {% if object.club.website %}
            <tr>
                <td>Website</td>
                <td><a href="{{ object.club.website }}" target="_blank" rel="noopener">{{ object.club.website }}</a></td>
            </tr>
            {% endif %}
{#            <tr>#}
{#                <td>Managed by</td>#}
{#                <td><a href="{% url "callsign:callsign-html-detail" object.owner.primary_callsign %}">{{ object.owner.primary_callsign }}</a></td>#}
{#            </tr>#}
            {% if object.club.members.all %}
            <tr>
                <td>Members</td>
                <td>
                  <ul>
                    {% for member in object.club.members.all %}
                    <li><a href="{% url "callsign:callsign-html-detail" member.name %}">{{ member.name }}</a></li>
                    {% endfor %}
                  </ul>
                </td>
            </tr>
            {% endif %}
            {% if object.club.description %}
            <tr>
                <td>Description</td>
                <td>{{ object.club.description }}</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
    </div>
    <!-- /.box-body -->
</div>